# Data methodology {#appendix-datamethods}

::: {.open data-latex=""}
This chapter provides links to documents that explain specific methodologies used for data analysis in this report. All links are PDF documents.
:::

## Quantifying the availability of "starter homes" in Virginia

This analysis estimates the number and share of homes sold in Virginia jurisdictions that could be defined as “starter homes.” The goal is to better understand how options for first-time home buyers vary across the Commonwealth and how the inventory of starter homes has changed over the past eight years. Sales data from the Virginia REALTORS® and income data from the U.S. Department of Housing and Urban Development are used.

Results of this analysis are in [Chapter 15](#part-3-homeownership).

[Data methodology: Quantifying the availability of “starter homes” in Virginia](https://www.hb854housingstudy.org/pdf/hb854-methods-starterhomes.pdf) (PDF)

## Determining the income needed to afford the median home sales price

This analysis was used to make comparisons between the median renter household incomes and income needed to afford the median home sales price in Virginia localities. This analysis was conducted using American Community Survey data on median renter household incomes at the locality-level in Virginia, as well as median sales price data from the Virginia REALTORS®.

Results of this analysis are in [Chapter 15](#part-3-homeownership).

[Data methodology: Determining the income needed to afford the median home sales price](https://www.hb854housingstudy.org/pdf/hb854-methods-incometoafford.pdf) (PDF)

## Estimating the cost of a state-funded rental assistance program

This analysis provides a general estimation of four possible scale options for a state-funded rental assistance program in Virginia. The scenarios are based on general assumptions about assistance amounts and administrative costs.

Results of this analysis are in [Chapter 26](#part-5-staterental).

[Estimating the cost of a state-funded rental assistance program](https://www.hb854housingstudy.org/pdf/hb854-methods-rentscenarios.pdf) (PDF)
