# Property tax reduction {#part-5-propertytax}

::: {.open data-latex=""}
This chapter addresses HB854's requirement to propose recommendations for *"real property tax reduction for qualified affordable housing for localities that desire to provide such an incentive."*
:::

## Highlights {.unnumbered .unlisted}

Major takeaways in this chapter include:

* Property taxes on affordable housing generate needed revenue for localities, but they can often serve as a barrier to development and preservation.
* Stakeholders endorse a new amendment to the state constitution that would enable---not require---local governments to use a wide range of alternative real estate tax schemes for properties used for affordable housing and homelessness services. Potential solutions include full and partial exemptions, abatements, and Payment in Lieu of Tax (PILOT) programs.
* While current state code directs local assessors to account for rent restrictions in some types of affordable rental housing, providers must often appeal incorrect valuations, leading to sunk costs. Minor code changes, along with expanded outreach to local assessors, would significantly reduce these challenges.

## Background

HB854 requests the SAG to:

> *". . . consider the following proposals as well as other proposals it considers advisable during the course of its analysis and deliberations: . . . **real property tax reduction for qualified affordable housing for localities that desire to provide such an incentive** . . ."*

Local real estate taxes are one of the many costs of creating affordable housing, but are also the primary revenue generator for local governments. Property tax reductions allow municipalities to support affordable housing for the duration of the benefit, replacing or supplementing upfront capital subsidies.

## Findings

### Tax reduction mechanisms

In Virginia, localities can reduce real estate tax burdens through tax exemption or tax abatement.

**Tax exemption**

A tax exemption on a property makes it "immune from real estate taxation" within a county, city, or town.[^part-5-28-1] A locality can grant an exemption to certain properties or property owners only if the local government has been so authorized by the Virginia Constitution and/or an act of the General Assembly. Depending on statute, exemptions may be total or partial.

[^part-5-28-1]: Va. Code Ann. § [58.1-3604](https://law.lis.virginia.gov/vacode/title58.1/chapter36/section58.1-3604/). "Tax exemption information."

**Tax abatement**

A tax abatement reduces the taxable value of a property for a prescribed period usually as an incentive to conduct significant repair, rehabilitation, or construction. The taxable amount is locked into a pre-improvement value for a period of time, as established by an ordinance. This temporarily reduces the tax burden, helping the property owner finance needed upgrades to a structure, or in some cases, a total replacement.[^part-5-28-2]

[^part-5-28-2]: In some cases, "partial tax exemption" and "tax abatement" are used interchangeably. For the purposes of this report, "tax abatement" will refer specifically to temporary real estate tax reductions that expire after a period of time.

Both mechanisms may be considered as "property tax reductions" in accordance with HB854. This subgroup will explore exemption and abatement mechanisms in its recommendations.

Tax exemption and tax abatement are distinct from **tax credits**, which are generally dollar-for-dollar reductions in tax liability for earned income. Although different forms of tax influence housing development and housing markets, this report focuses on reducing taxes associated with property values rather than incomes.

### Constitutional and legal framework

**Constitutional provisions**

The Virginia Constitution provides localities with options for exempting residential real estate under certain conditions:[^part-5-28-3]

[^part-5-28-3]: Va. Const. Art X, § 6. [Exempt property](https://law.lis.virginia.gov/constitutionexpand/article10/).

* A *total or partial* exemption for dwellings owned and occupied by persons not less than 65 years of age or persons permanently and totally disabled. Localities may establish "income or financial worth limitations, or both" to set eligibility criteria for exemptions.
* A *partial* exemption for real estate "whose improvements . . . have undergone substantial renovation, rehabilitation or replacement" or real estate "with new structures and improvements in conservation, redevelopment, or rehabilitation areas."

::: {.info data-latex=""}
**Mandatory property tax exemptions study**

In early 2021, state lawmakers asked the Commission on Local Government to study "the fiscal effects of mandatory property tax exemptions on the capacity of local governments to deliver essential services to the public." (See: [Appropriation Act - Item 359 \#4c](https://budget.lis.virginia.gov/amendment/2021/2/HB1800/Introduced/CR/114/4c/), 2021 Special Session I, Virginia General Assembly.)

The report was [completed](https://rga.lis.virginia.gov/Published/2021/RD643/PDF) in November 2021 and includes recommendations to mitigate any detrimental effects created by these requirements.
:::

**Proposed 2021 constitutional amendment**

In 2021, Delegate Jeffrey Bourne proposed a constitutional amendment to authorize localities to exempt certain affordable housing from real property taxes.^[[HJ616](https://lis.virginia.gov/cgi-bin/legp604.exe?211+sum+HJ616) Constitutional amendment; real property tax exemption for affordable housing. 2021 Session, Virginia General Assembly.] The resolution was passed by in committee. As drafted, it would have amended Section 6 of Article X of the state constitution as follows:

> *"The General Assembly may by general law authorize the governing body of any county, city, town, or regional government to provide for the exemption from local real property taxation, or a portion thereof, within such restrictions and upon such conditions as may be prescribed, of real estate on which affordable housing, as defined by the General Assembly, is constructed."*

**Current state code**

In accordance with constitutional provisions, state law provides localities with specific guidance on housing-related exemption and abatement options. Relevant examples include:

*§ [36-157 et seq](https://law.lis.virginia.gov/vacode/title36/chapter11/). Housing Revitalization Zone Act.*

The passage of the Housing Revitalization Zone Act in 2000 intended to create performance-based grants to encourage rehabilitation of designated residential zones by private sector investment. At least one quarter of real estate tax revenues from such areas would then be reserved for additional investments in those zones. The unfunded program has never been implemented.

*§ [58.1-3219.4](https://law.lis.virginia.gov/vacode/title58.1/chapter32/section58.1-3219.4/). Partial exemption for structures in redevelopment or conservation areas or rehabilitation districts.*

In 2006 lawmakers authorized local governments to grant partial real estate tax exemptions for:[^part-5-28-5]

[^part-5-28-5]: [SB358](https://lis.virginia.gov/cgi-bin/legp604.exe?061+sum+SB358) Real estate tax; exemption in redevelopment or conservation areas, etc. 2006 Session, Virginia General Assembly.

* (i) new structures located in redevelopment or conservation areas or rehabilitation districts, and
* (ii) other improvements to real estate located in redevelopment or conservation areas or rehabilitation districts.

Local ordinances establish such districts and areas. Exemption amounts are based on a share of the increase in an eligible property's assessed value. Many localities across Virginia currently use this provision to encourage residential revitalization in certain neighborhoods. In 2020 lawmakers extended the maximum possible exemption period from 15 years to 30 years.[^part-5-28-6]

[^part-5-28-6]: [SB727](https://lis.virginia.gov/cgi-bin/legp604.exe?201+sum+SB727) Real estate tax; exemption for property in redevelopment or conservation areas. 2020 Session, Virginia General Assembly.

*§ [58.1-3220](https://law.lis.virginia.gov/vacode/title58.1/chapter32/section58.1-3220/). Partial exemption for certain rehabilitated, renovated or replacement residential structures.*

Similar to § 58.1-3219.4, this provision authorizes local governments to grant partial real estate tax exemptions for certain properties with structures more than 15 years old that undergo "substantial rehabilitation, renovation or replacement for residential use." Localities can establish eligibility criteria in an ordinance. This code has been amended numerous times since its inception over 40 years ago.

*§ [58.1-3221](https://law.lis.virginia.gov/vacode/title58.1/chapter32/section58.1-3221/). Partial exemption for certain rehabilitated, renovated or replacement commercial or industrial structures.*

Drafted and adopted in conjunction with § 58.1-3220, this code allows localities to grant similar partial real estate tax exemptions for properties that undergo "substantial rehabilitation, renovation or replacement for commercial or industrial use." Buildings must be at least 20 years old, or 15 years old if located in an enterprise zone or technology zone pursuant to § 58.1-3850. No language in this section precludes "commercial use" from including multifamily apartment and mixed-use buildings.

*§ [58.1-3622](https://law.lis.virginia.gov/vacode/title58.1/chapter32/section58.1-3622/). Habitat for Humanity and local affiliates or subsidiaries thereof.*

Passed in 2000, this code classifies nonprofit Habitat for Humanity entities as "charitable and benevolent" organizations that are exempt from local real estate taxes. State lawmakers derive their authority to grant this exemption from Article X, Section 6 (a) (6) of the Constitution of Virginia. Local governments must pass a resolution for Habitat affiliates to receive this exemption.

The scale, scope, and effectiveness of these various provisions have never been systematically studied or evaluated, particularly with respect to their ability to spur additional investments in housing and lower housing costs.

### State guidance to assessors for affordable housing

Va. Code Ann. § [58.1-3295](https://law.lis.virginia.gov/vacode/title58.1/chapter32/section58.1-3295/) directs localities to assess below-market rate (affordable) rental housing after considering:

1.  Restrictions on rent values,
2.  Restrictions on title transfers and "other restraints" on future sale, and
3.  "Actual operating expenses" and other relevant expenditures.

These considerations ensure that the owners of affordable rental housing are levied real estate taxes commensurate with the actual rent amounts collected rather than fair market values. This should reduce the tax burden on these properties.

Multiple owners have expressed concern that local assessors have neglected to follow these provisions correctly, resulting in burdensome real estate taxes relative to actual operating revenue. Tax assessors in different jurisdictions sometimes approach this valuation differently, complicating development for entities that work across more than one locality.

::: {.data data-latex=""}
One affordable rental provider interviewed for this report testified they spend about **100 hours each year on appeals and hearings** just to get their properties correctly valued by localities.
:::

Current code does not cover all types of affordable rental housing found in the state:

**Covered by § 58.1-3295:**

* Low-Income Housing Tax Credit (both nine percent and four percent)
* Project-based Vouchers
* HUD 236
* HUD 241f
* HUD 221(d)3

**Not covered by § 58.1-3295:**

* USDA Rural Development (Section 515)
* HUD 202
* HUD 811
* Rental Assistance Demonstration (RAD)
* Properties that are entirely funded/supported by localities

### Impact of high tax burdens on affordable housing

Based on stakeholder interviews and research, this subgroup finds that:

* In Virginia, real estate taxes often average five to ten percent of an affordable housing property's expenses. This can translate to roughly one month's rent for tenants, increasing their rent burdens.
* Property tax reductions can have significant impact because developers and owners can leverage reductions into total financing for the property, lowering overall debt and reducing rents. At current low interest rates, this leverage can be ten to one; however, any tax reduction must be long-term for underwriting purposes.
* Lowering operating expenses through tax reductions raises net operating income, increasing mortgage proceeds available to pay down debt.

## Recommendations

In early 2021, the HB854 property tax reduction subgroup met four times to discuss how the state can lower real estate tax burdens for affordable housing. Based on discussions with experts from across the state and input from members of the subgroup, the subgroup makes the following recommendations.

### Recommendation 1 {.unlisted .unnumbered}

#### Give localities more tools to reduce tax burdens on dedicated affordable housing serving low-income Virginians. {.unlisted .unnumbered}

Rather than enacting statewide mandates, the General Assembly should pursue measures that give cities and counties new, flexible policy options for reducing real estate tax burdens on affordable housing properties. These solutions require changes to both the Constitution of Virginia and state code.

#### Strategy 1.1 {.unlisted .unnumbered}

*Support a new amendment to the state constitution allowing localities, at their option, to set up a Payment in Lieu of Taxes (PILOT) program or similar abatement/exemption options for affordable housing.*

PILOT initiatives allow affordable housing developers and localities to enter into mutually beneficial agreements that lower property tax burdens. Current Virginia law does not give localities proper authority to establish PILOT programs for affordable housing. It is already common practice for new affordable rental housing in Maryland and other states.

While PILOT programs may be the most common solution enabled by this proposal, the subgroup suggests that any amendment language be flexible enough to allow other similar types of relief policies.

::: {.open data-latex=""}
**Action items:**

**Task 1.1.1:** Draft language for an amendment to the Constitution of Virginia that:

* Explicitly permits all localities in Virginia to adopt ordinances that allow alternative real estate property tax collection schemes for properties used as affordable housing,
* Is written to broadly permit PILOT programs, abatements, exemptions, and other similar solutions that allow localities flexibility and options,
* Sets a minimum floor of 15 years for any period of tax reduction by local programs,
* Considers pro-rata tax relief to provide greater relief as deeper affordability is offered (covering mixed-income housing, and properties with units under inclusionary zoning programs, which may have some units rented above 80 percent AMI), and
* References definitions of affordable housing in state code if necessary.

Options for defining affordable housing are below.

* **Who:** Advocates and lawmakers

**Task 1.1.2:** Determine whether this amendment would require any reference to a definition or definitions of affordable housing in state code. Subgroup members recommend that any definition---whether current or new---should at a minimum:

* Cover all existing types of publicly-assisted multifamily rental housing, including LIHTC, USDA-RD Section 515, and others,
* Include as eligible uses affordable homeownership programs, homelessness services, and community land trusts and other shared-equity ownership models,
* Not be restricted to new construction only, and
* Defer most specific definitions/criteria to localities as they create ordinances under this new authority.

Currently, Va. Code Ann. § [15.2-2201](https://law.lis.virginia.gov/vacode/title15.2/chapter22/section15.2-2201/) provides the following definition of affordable housing for localities to use in the creation of land use and zoning regulations:

*"...housing that is affordable to households with incomes at or below the area median income, provided that the occupant pays no more than thirty percent of his gross income for gross housing costs, including utilities. For the purpose of administering affordable dwelling unit ordinances authorized by this chapter, local governments may establish individual definitions of affordable housing and affordable dwelling units including determination of the appropriate percent of area median income and percent of gross income."*

* **Who:** Advocates and lawmakers
:::

#### Strategy 1.2 {.unlisted .unnumbered}

*Allow localities more flexibility to provide tax incentives that support affordable manufactured home communities and the replacement of older, poor-quality mobile homes with new units.*

Manufactured home communities (MHCs) are one of the largest sources of unsubsidized affordable housing across the country and in Virginia. These properties would be mostly excluded from the solutions described in Strategy 1.1 because they do not receive public assistance and do not have dedicated affordability restrictions.

State policymakers can still create greater opportunities for localities to improve and preserve these communities through advantageous tax treatments.

::: {.open data-latex=""}
**Action items:**

**Task 1.2.1:** Mandate localities to assess manufactured homes in lot-lease communities (e.g., mobile home parks) as real estate rather than as personal property. This would enshrine an already common practice across the state, and help homeowners pay lower tax rates.

* **Who:** Advocates and lawmakers

**Task 1.2.2:** Amend state code to allow localities to waive or reduce disposal fees for obsolete, uninhabitable manufactured homes. Consider expanding such incentives to other/all types of vacant and distressed properties.

* **Who:** Advocates and lawmakers

**Task 1.2.3:** Allow localities to offer certain tax breaks and other incentives (e.g., waiver of recordation fees) to nonprofit organizations and resident cooperatives who purchase a manufactured home community with the intent to preserve its current use.

May also expand eligibility to private owners in certain scenarios, such as enforceable commitments to tenant protections and/or infrastructure investments. [Duty to Serve](https://www.fhfa.gov/PolicyProgramsResearch/Programs/Pages/Duty-to-Serve.aspx) quality criteria for MHCs (drafted by Fannie Mae) could be useful standards to apply.

* **Who:** Advocates and lawmakers

**Task 1.2.4:** Consider expansion of any affordable housing definition established by Strategy 1.1 to include manufactured home communities owned and operated by mission-oriented entities with certain affordability provisions, as well as manufactured home subdivisions.

* **Who:** Advocates and lawmakers

**Task 1.2.5:** Allow localities to offer reduced taxes, fees, and hookup costs for new manufactured home subdivisions. Possible mechanism is amending Va. Code Ann. § 15.2-958.4.

* **Who:** Advocates and lawmakers

**Task 1.2.6:** Study potential for localities to use tax-increment financing (TIF) districts specific to manufactured home communities to fund strategic investments in these neighborhoods. TIF funds could be used for:

* Water, septic, and other necessary infrastructure upgrade,
* Replacement unit assistance funds,
* Relocation funds for displaced residents, and
* Park preservation activities.

Example: [Living Cully Community-Led Development District](http://www.livingcully.org/tif/about/) in Portland, Oregon.

* **Who:** HousingForward Virginia, Manufactured Home Community Coalition of Virginia, and other stakeholders

**Task 1.2.7:** Study potential for statewide tax credit (rather than tax abatement) that covers a significant portion of cost associated with replacement of obsolete mobile homes with new, high-quality manufactured homes.

* **Who:** HousingForward Virginia, Manufactured Home Community Coalition of Virginia, and other stakeholders
:::

#### Strategy 1.3 {.unlisted .unnumbered}

*Streamline, improve, and promote current state code sections that allow localities to reduce tax burdens for affordable housing in certain districts.*

The Code of Virginia currently includes numerous districts that localities may establish (under certain conditions) which permit special tax treatment of specific developments. Real estate tax abatements are the most common option allowed. While affordable housing development has an important connection to many of these districts, the number and complexity of these districts can make it difficult to make those links.

To date, the state has not conducted a comprehensive review of these districts. This subgroup is unable to make specific recommendations without an analysis. State policymakers should commission a study that assesses the timeline, scale, and impact of these districts. Such a study should consider repositioning special districts to promote affordable housing development in high opportunity areas rather than only in communities with historically low levels of investment.

::: {.open data-latex=""}
**Action items:**

**Task 1.3.1:** Determine the preferred method for commissioning and undertaking this study. Possible entities that would be responsible for overseeing this work include the Virginia Housing Commission.

Evaluate whether state housing staff could complete the necessary research or would require a consultant such as a university.

Estimate state budget implications and prioritize work relative to other agency activities.

* **Who:** DHCD and Virginia Housing

**Task 1.3.2:** Outline study components and research questions to be addressed. Report should cover:

* Original goals of each district,
* Number per applicable locality for each district type,
* Scope of housing development or operation benefitting from each district,
* Timeframe of local adoption of these districts,
* Analysis of strengths, weaknesses, and opportunities, and
* Recommendations for changes to state code.

The report would be delivered to the General Assembly and appropriate stakeholders.

* **Who:** DHCD and Virginia Housing
:::

### Recommendation 2 {.unlisted .unnumbered}

#### Promote fair, accurate, and predictable tax assessment of affordable housing. {.unlisted .unnumbered}

Both developers and operators of affordable housing properties have highlighted significant challenges with the assessment process for rent-restricted communities. These problems stem from insufficient language in state code. Policymakers should resolve this issue by amending code, and establishing a permanent system to resolve future conflicts.

#### Strategy 2.1 {.unlisted .unnumbered}

*Strengthen Va. Code Ann. § 58.1-3295 to include additional affordable housing types.*

The current section of state code that directs local real estate assessors to use a specific income-based approach for rent-restricted affordable housing needs revision. The code should be amended to cover all types of rental housing that use subsidies to serve households below 80 percent AMI.

::: {.open data-latex=""}
**Action items:**

**Task 2.1.1:** Draft new language to replace certain sections of Va. Code § 58.1-3295 with a broader definition of affordable housing.

The new definition should use one of the following solutions.

1.  Explicitly reference the major forms of affordable rental housing excluded in the current code, including:

* USDA Rural Development,
* HUD Section 202,
* HUD Section 811,
* Rental Assistance Demonstration, and others.

2.  Align with any possible definition of affordable housing proposed above in Task 1.1.2 of this chapter.

Either route will significantly expand the number of properties covered under this requirement.

* **Who:** Advocates and lawmakers
:::

#### Strategy 2.2 {.unlisted .unnumbered}

*Create a standing statewide committee or task force to monitor and promote fair assessment of affordable housing by localities.*

Rental housing practitioners have catalogued specific challenges related to incorrect valuation of affordable housing by local assessment officials. Providers pay a larger amount of real estate taxes on these misvalued properties than state code actually requires.

Along with the necessary change to state code described in Strategy 2.1 of this chapter, policymakers should create a new permanent task force that offers additional training, resources, education, and conflict resolution opportunities. This group will work to achieve greater consistency and predictability for the assessment of affordable housing.

::: {.open data-latex=""}
**Action items:**

**Task 2.2.1:** Gather stakeholders to determine the most appropriate apparatus of state government to fulfill this task.

These stakeholders should include:

* State Department of Taxation
* Auditor of Public Accounts
* Virginia Association of Commissioners of Revenue
* Virginia Housing Commission staff
* Affordable housing developers and owners
* DHCD and Virginia Housing

Other stakeholder may be added as appropriate.

* **Who:** Advocates and lawmakers

**Task 2.2.2:** Propose major elements of this new entity, including:

* Membership criteria and appointment process,
* Mission, roles, and responsibilities,
* Conflict resolution process (between property owners and localities),
* Ability to levy penalties to localities with multiple substantiated complaints,
* Meeting schedule, and
* Permanent funding levels needed in the state budget to sustain staffing and operations of this body.

Lawmakers would ultimately be responsible for funding this entity.

* **Who:** Advocates and lawmakers
:::
