# How we use data {#part-1-data}

:::{.open data-latex=""}
This chapter introduces the most common data sources used for this study and the definitions for demographic categories, such as race and ethnicity identifiers, used throughout the report.
:::

## Common data sources 

Below is a description of some of the most common data sources that inform this study.

**American Community Survey**

The [American Community Survey](https://www.census.gov/programs-surveys/acs) (ACS) is an ongoing survey program of the U.S. Census Bureau. The ACS collects information about the nation’s social, economic, housing, and demographic characteristics on an annual basis. This information provides the most-up-to-date estimates between decennial censuses.

This study uses two types of ACS data:

1. 5-Year Estimates are averages across a five-year period. This type of data is available for all geographic levels. Although it is the least current data, it is considered the most reliable due to its large sample size.
2. 1-Year Estimates are averages across a 12 month period. This type of data is available only for areas with populations of 65,000 or more people. Although less reliable because it uses the smallest sample size, this data is the most current. This report uses 1-Year Estimates when reporting median dollar amounts to avoid the distortion created by calculating medians over several years (as in the case of 5-Year Estimates).

**Building Permits Survey**

The [Building Permits Survey](https://www.census.gov/construction/bps/) is a program of the U.S. Census Bureau that provides national, state, and local data on new privately-owned residential construction. The survey releases data on an annual and monthly basis. Information collected by the survey includes the number of buildings, number of housing units, and permit valuation by size of the structure. 

**Comprehensive Housing Affordability Strategy**

The U.S. Census Bureau creates custom tabulations of ACS data and provides them to HUD on an annual basis. Known as [Comprehensive Housing Affordability Strategy](https://www.huduser.gov/portal/datasets/cp.html) (CHAS) data, they indicate the extent of housing problems and needs throughout the nation.

CHAS data are the primary source of information regarding housing cost burden. Although released on an annual basis, CHAS data do lag behind more current ACS estimates. At the time of this report, the most recent CHAS data release was for the 5-Year Estimate period from 2013 to 2017.

**Home Mortgage Disclosure Act**

The [Home Mortgage Disclosure Act](https://www.consumerfinance.gov/data-research/hmda/) (HMDA) requires that financial institutions maintain, report, and disclose loan-level information about mortgages. This information provides a level of transparency around home lending and informs policy decisions. All publicly published data is de-identified to protect applicant and borrower privacy. Data collected through HMDA includes demographic information about applicants and details about the loan and the home-to-be-purchased.

**HUD Point-in-Time and Housing Inventory Count**

HUD requires that Continuums of Care (CoC) conduct and report an annual count of people experiencing homelessness within their service areas. These counts include people experiencing homelessness currently in emergency shelters, transitional housing, and Safe Havens on a single night, as well as unsheltered people experiencing homelessness observed on-the-street. These counts are referred to as [Point-in-Time](https://www.hudexchange.info/programs/coc/coc-homeless-populations-and-subpopulations-reports/) (PIT) counts.

The [Housing Inventory Count](https://www.hudexchange.info/programs/coc/coc-housing-inventory-count-reports/) (HIC) is a PIT inventory of provider programs within a CoC that provide beds and units dedicated to people experiencing homelessness or who were homeless at entry. This includes emergency shelters, transitional housing, rapid re-housing, Safe Havens, and permanent supportive housing.

**Local Area Unemployment Statistics**

The [Local Area Unemployment Statistics](https://www.bls.gov/lau/) (LAUS) program is a program of the U.S. Bureau of Labor Statistics. This program produces monthly and annual employment, unemployment, and labor force data for all geographic levels of the country.

**National Housing Preservation Database**

The [National Housing Preservation Database](https://preservationdatabase.org/) (NHPD) is a partnership between the National Low-Income Housing Coalition (NLIHC) and Public and Affordable Housing Research Corporation (PAHRC). The NHPD provides property-level and subsidy-level data from nine different HUD and USDA data sources in a single database. 

**Population and Housing Units Estimates Program**

The [Population Estimates Program](https://www.census.gov/programs-surveys/popest.html) (PEP) is a program of the U.S. Census Bureau that provides an informed estimation of population and housing units for all states and counties on an annual basis. The U.S. Census Bureau estimates resident populations and housing units each year following a decennial census by using the measures of population change and components of housing change.

Other survey programs such as the ACS and American Housing Survey (AHS) use the data as controls. Population estimates from PEP inform federal funding allocations.

**Project HOPE Education for Homeless Children and Youth**

The William and Mary School of Education’s [Project HOPE](https://education.wm.edu/centers/hope/) serves as the administrator of Virginia’s Program for the Education of Homeless Children and Youth on behalf of the Virginia Department of Education. Project HOPE tracks the number of homeless children and youth enrolled in Virginia’s public schools based on the Department of Education’s definition of homelessness.

**Occupational Employment and Wage Statistics**

The [Occupational Employment and Wage Statistics](https://www.bls.gov/oes/) (OEWS) program is a product of the U.S. Bureau of Labor Statistics. OEWS provides annual employment and wage estimates for roughly 800 different occupations in the United States. 

**Virginia Association REALTORS® Multiple Listing Service**

A Multiple Listing Service (MLS) is a real estate database used by licensed REALTORS® to facilitate the buying and selling of homes in the United States. These systems provide a dynamic snapshot of home prices and home sales, as well as information on the characteristics of those homes. [Virginia REALTORS®](https://virginiarealtors.org/) provided statewide data from MLS databases across the Commonwealth.

**Weldon Cooper Center for Public Service Population Projections**

The University of Virginia’s [Weldon Cooper Center for Public Service](https://demographics.coopercenter.org/) produces population projections for the Commonwealth of Virginia and its cities, counties, and large towns. The center also produces population projections for all fifty U.S. states and the District of Columbia. Federal agencies, state governments, businesses, and nonprofit entities now use these projections for their particular planning and research needs because the U.S. Census Bureau stopped producing state-level population projections this past decade.

## Common terms

The following list provides definitions for several data categories used throughout this study:

### Race

When referring to a specific race, that race is non-Hispanic. For example, Black households are specifically Black, non-Hispanic households, unless specified otherwise.

**Another race** most often refers to the U.S. Census Bureau’s category of "Some Other Race," which includes all responses not included in the white, Non-Hispanic, Black or African American, American Indian and Alaska Native, Asian, and Native Hawaiian and Other Pacific Islander categories. For visual clarity, we often aggregate American Indian and Alaska Native and Native Hawaiian and Other Pacific Islander---a small proportion of the data---into the "Another race" category.

**Multiracial** refers to the U.S. Census Bureau’s category of "Two or More Races."

**Hispanic** is referred to throughout this study in place of "Hispanic or Latino." Hispanic and Latino are both pan-ethnic terms used to describe people living in the United States who identify as being from Spain or from Spanish-speaking countries and from Latin American countries regardless of language. We recognize that there are distinctions between the two terms; however, for the sake of brevity and consistency we use the term Hispanic.

**White, non-Hispanic** refers to individuals who do not identify as Hispanic or Latino and who have reported their race as "white" only.

### Housing

**Area median income (AMI)** is the midpoint of a region’s income distribution (i.e., half the households in a region earn more than that figure while the other half make less). AMI is used frequently as a benchmark to set income limits in housing policy. HUD sets different AMI levels based on different geographic areas and household sizes.

**Cost-burdened** refers to a household that spends more than 30 percent of their gross household income on housing costs, including utilities. For greater nuance, a household that spends more than 50 percent is severely cost-burdened.

**Home(s)** refers to what the U.S. Census Bureau defines as "housing units." A housing unit is a house, apartment, a group of rooms, or a single room occupied or intended for occupancy as separate living quarters.

**Household** refers to all individuals that reside under a single roof. A household typically comprises a family, but can include non-related individuals that live together.

**Householder** refers to the primary individual owning or renting a home. This individual may be either spouse if the household consists of a married couple. 

**Manufactured home** refers to a factory-built home that is fully built on a chassis. These homes are built to meet standards promulgated by the U.S. Department of Housing and Urban Development (the "HUD Code").

**Modular home** (or a prefabricated home) is a home that is built to near completion (typically 80 to 90 percent) and then transported to a location and fully assembled on site. These homes are built to state and local building codes.

**Multifamily** refers to a building that contains more than one housing unit. For the purposes of this study, different multifamily densities are defined as follows:

* **Small-scale multifamily** is a building that consists of 2 to 19 housing units. This includes duplexes, triplexes, and other similar buildings of three stories or fewer.
* **Medium-scale multifamily** is a building that consists of 20 to 49 housing units. This typically includes low-rise and mid-rise apartments.
* **Large-scale multifamily** is a building that consists of 50 or more housing units. This typically includes mid-rise and high-rise apartments.

### Income

**Extremely low-income (ELI)** households are households that earn 30 percent of AMI or below.

**Very low-income (VLI)** households are households that earn between 31 and 50 percent AMI.

**Low-income (LI)** households are households that earn between 51 and 80 percent AMI.

**Asset Limited, Income Constrained, Employed (ALICE)** is a term used to describe working households that are not technically in poverty, but are unable to afford all the basic necessities like housing, food, and health care.

::: {.info data-latex=""}
More information about ALICE, including specific methodology, can be found on the [United for ALICE](https://www.unitedforalice.org/state-overview/Virginia) campaign website. This effort is led by the United Way of Northern New Jersey; multiple United Way affiliates in Virginia also participate as partners.
:::

### Age

**Generation Z** (or Gen-Zers) generally refers to people born between 1997 and now. As of 2021, these people are under 24 years old.
 
**Millennial(s)** generally refers to a person or people born between 1981 and 1996. As of 2021, these people are 25 to 40 years old.
 
**Generation X** (or Gen-Xers) generally refers to people born between 1965 and 1980. As of 2021, these people are 41 to 56 years old.

**Baby boomer(s)** generally refers to a person or people born between 1946 and 1964. As of 2021, these people are 57 to 75 years old.

**Silent generation** generally refers to people born between 1928 and 1945. As of 2021, these people are 76 to 93 years old.